In [6]:
#Question 1
import numpy as np
array = np.array([1,2,3,4,5])
lis = array.tolist()
print(lis)

[1, 2, 3, 4, 5]


In [25]:
#Question 2
import numpy as np 
s = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
trace = np.trace(s)
print(trace)

15


In [39]:
#Question 3
a = np.array([[1,2],[3,5]])
a[a > 2]

array([3, 5])

In [45]:
#Question 4
import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = np.zeros_like(A)

for i in range(A.shape[0]) :
    for j in range(A.shape[1]) :
        C[i, j] = A[i, j] + B[i, j]
print(C)

[[ 6  8]
 [10 12]]


In [31]:
#Question 5
s-s.mean(axis=1, keepdims=True)

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])